spring:
  application:
    name: stase

  external-api:
    igdb-api: "https://api.igdb.com/v4/games"
    igdb-secret: "apd52sehy7ug7ctcm1g44svggqcmn0"
    igdb-id: "tpk7gintwrv8cuau622qzkaywlf8ep"
    rawg-api: "28613bab46d54ef89b1b572c43d6b0ed"
    rawg-url: "https://api.rawg.io/api"
    steam-api: ""

  datasource:
    url: jdbc:postgresql://localhost:5432/stase
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
