spring:
  application:
    name: stase

  external-api:
    igdb-url: "test"
    rawg-url: ""
    steam-url: ""

  datasource:
    url: jdbc:postgresql://localhost:5432/stase
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
